name: Linting, testing and building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipelline:
    runs-on: macos-latest
    strategy:
      matrix:
        node_version: [ 19.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version:
            ${{ matrix.node-version }}
      - run: npm ci
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: building storybook
        run: npm run storybook:build
      - name: ui testing
        run: npm run test:ui:ci:macos
